version: '2'
services:
    sude-app:
        image: sude
        external_links:
            - sude-mysql:mysql
            - sude-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sude?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    sude-mysql:
        extends:
            file: mysql.yml
            service: sude-mysql
    sude-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sude-elasticsearch
